### ISSUE TITLE
bikeways dataset - Glenoaks Blvd

### ISSUE THREAD

**Issue by RyanTG** [SCPR/kpcc-data-team#15]
BPID 2045 (installed 2/13/2013) overlaps with BPID 248 (installed pre-1/1/2005).

I believe the LADOT spreadsheet on bikeway projects per fiscal year is incorrect. It states that BPID 2045 extends from Paxton St. to Terra Bella St. But according to google streetview (going back to 2007) there was already a bike lane from Terra Bella to Van Nuys Blvd. And BPID 248 backs this up. 

Perhaps LADOT considered the repainting of this bike lane to be a new project? I dunno.

EDIT: and thanks for dataset! It's great, and much-needed.

**Comment by chrislkeller** [comment]
Thanks @RyanTG ... Flagging @amendelson who worked on compiling this dataset.

**Comment by amendelson** [comment]
@RyanTG thanks for the head's up, I'll let the city know. At this point they likely have updated this dataset, if you get in touch at amendelson AT scpr DOT org I can let you know how to request it from them.

Are you using the bikeways data? I'd love to know if so. Just saw your LAC CrashBot, that's really cool.

**Comment by RyanTG** [comment]
Thanks! Yes, I'm using your data. My project is still in progress. I've used it for a before/after crash analysis of new bikeways as a function of ridership (using LACBC's ridership data). The results will be in the LACBC's upcoming bike count report. And they'll also be, in more detail, in my UCLA urban studies capstone project. It's due in a few weeks!

I've also used it for a crash analysis in the Lewis Center at UCLA - that's also an ongoing project.

Yours is the best bikeways dataset for the City of LA.

**Comment by amendelson** [comment]
Have you compared [to this](http://geohub.lacity.org/datasets/230abc621b144dbc96cca83d65bd454d_0)? It's possible there's newer information available there.

Anyway, I'm curious to see what you find in your projects. Drop me a line when you finish them.

**Comment by RyanTG** [comment]
No, I haven't. When that was published, I had already started my project and picked my study sites. So I didn't bother.

But I just looked now, and the issue I brought up here is not corrected. Also, "Paxton St" is spelled wrong for BPID 1991 (this observation has nothing to do with anything! I just happened to notice it).
